### ISSUE TITLE
Is it possible to use this function to make Bilinear Reverse?

### ISSUE THREAD

**Issue by sunsetninja** [AdeonMaster/canvas-arbitrary-quads#2]
Thank you for great work!

Can you please help figure out: is it possible to use your function to achieve this result?

![image](https://user-images.githubusercontent.com/13559663/139070056-f0beb2f3-82d0-4b0a-8848-fc8e6013b3d1.png)

**Comment by AdeonMaster** [comment]
@sunsetninja hello and apologies for the late reply.. Yes, you can try to use this repo to do such transformation! Just set up your source & destination points as it shown here:
![image](https://user-images.githubusercontent.com/11544417/139705188-bbbf6a08-b409-4771-9ed7-f2853c7d875f.png)
